/**
 * Conduit reference CUF — GENERATED by the packaged Playwright Agents (Planner -> Generator, driven
 * via the playwright-test MCP against understudy's playwright.realworld.config.ts), NOT hand-authored.
 * It exists to validate the agent toolchain end-to-end on understudy's harness: the Planner explored
 * the live hermetic app, the Generator wrote this test from the recorded interactions, and it passes
 * the DETERMINISTIC gate (INV-1 — only Playwright runs in the gate; the LLM authored upstream).
 * Auth comes from the project storageState; data-independent (no seed) so it is hermetic on the
 * pristine-per-`up` DB.
 */
import { test, expect } from '@playwright/test'

test.describe('home and feed navigation (agent-generated)', () => {
  test('an authenticated user sees the home shell and switches to the Global Feed', async ({ page }) => {
    await page.goto('/')
    await expect(page.getByText('understudy-e2e')).toBeVisible()
    await expect(page.getByRole('link', { name: ' New Article' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Your Feed' })).toBeVisible()

    const globalFeed = page.getByRole('button', { name: 'Global Feed' })
    await expect(globalFeed).toBeVisible()
    await globalFeed.click()
    await expect(page.getByText('Articles not available.')).toBeVisible()
  })
})
