/**
 * Conduit — Popular Tags feed filtering CUF — GENERATED by the packaged Playwright
 * Agents (Planner → Generator, driven via the playwright-test MCP against understudy's
 * playwright.realworld.config.ts), NOT hand-authored.
 *
 * Verifies that clicking a Popular Tag in the sidebar opens an ephemeral feed tab
 * filtered to that tag, and that switching back to 'Global Feed' or 'Your Feed'
 * collapses the ephemeral tab. No seed needed — the 'e2e' tag exists from setup.
 */
import { test, expect } from '../fixtures'

test.describe('popular tags feed filtering (agent-generated)', () => {
  test('clicking a Popular Tag filters the Global Feed to show only that tag\'s articles', async ({ page }) => {
    // 1. Navigate to http://localhost:3000/#/ and assert page title, feed tabs, and Popular Tags sidebar
    await test.step('navigate to home and verify initial state', async () => {
      await page.goto('http://localhost:3000/#/')
      await expect(page).toHaveTitle(/Conduit/)
      await expect(page.getByRole('button', { name: 'Your Feed' })).toBeVisible()
      await expect(page.getByRole('button', { name: 'Global Feed' })).toBeVisible()
      await expect(page.getByRole('complementary').getByRole('button', { name: 'e2e' })).toBeVisible()
    })

    // 2. Click 'Global Feed' tab — assert it becomes active
    await test.step('click Global Feed tab and assert it is active', async () => {
      const globalFeedTab = page.getByRole('button', { name: 'Global Feed' })
      await globalFeedTab.click()
      await expect(globalFeedTab).toHaveClass(/active/)
    })

    // 3. Click the first tag 'e2e' in the Popular Tags sidebar
    //    assert: ephemeral third tab appears with tag name, that tab is active
    await test.step('click e2e tag in Popular Tags sidebar and assert ephemeral tab appears', async () => {
      const sidebarTag = page.getByRole('complementary').getByRole('button', { name: 'e2e' })
      await sidebarTag.click()

      // The ephemeral tag tab is the third button in the feed nav list (not in the sidebar)
      const feedTabList = page.getByRole('list').filter({ has: page.getByRole('button', { name: 'Your Feed' }) })
      const tagTab = feedTabList.getByRole('button', { name: /e2e/i })
      await expect(tagTab).toBeVisible()
      await expect(tagTab).toHaveClass(/active/)

      // Exactly three feed tabs visible
      await expect(feedTabList.getByRole('listitem')).toHaveCount(3)
    })

    // 4. Assert URL is still http://localhost:3000/#/
    await test.step('assert URL has not changed', async () => {
      await expect(page).toHaveURL('http://localhost:3000/#/')
    })

    // 5. Click 'Global Feed' tab — assert third tab disappears, only two tabs remain, 'Global Feed' is active
    await test.step('click Global Feed — ephemeral tab disappears and only two tabs remain', async () => {
      const globalFeedTab = page.getByRole('button', { name: 'Global Feed' })
      await globalFeedTab.click()

      const feedTabList = page.getByRole('list').filter({ has: page.getByRole('button', { name: 'Your Feed' }) })
      await expect(feedTabList.getByRole('listitem')).toHaveCount(2)
      await expect(globalFeedTab).toHaveClass(/active/)
      await expect(feedTabList.getByRole('button', { name: /e2e/i })).toHaveCount(0)
    })

    // 6. Click tag again then switch to 'Your Feed' — assert cleanup (ephemeral tab disappears)
    await test.step('click e2e tag again then switch to Your Feed — ephemeral tab disappears', async () => {
      const sidebarTag = page.getByRole('complementary').getByRole('button', { name: 'e2e' })
      await sidebarTag.click()

      const feedTabList = page.getByRole('list').filter({ has: page.getByRole('button', { name: 'Your Feed' }) })
      await expect(feedTabList.getByRole('listitem')).toHaveCount(3)

      const yourFeedTab = page.getByRole('button', { name: 'Your Feed' })
      await yourFeedTab.click()

      await expect(feedTabList.getByRole('listitem')).toHaveCount(2)
      await expect(yourFeedTab).toHaveClass(/active/)
    })
  })
})
